import type { EtfCategory } from "@/types/etf";

export interface FallbackEtfPoolItem {
  etfCode: string;
  etfName: string;
  category: EtfCategory;
  direction: string;
  trackingIndexCode: string | null;
  trackingIndexName: string | null;
  aumYi?: number | null;
  avgDailyTurnoverYi?: number | null;
  premiumDiscount?: number | null;
  expenseRatio?: number | null;
}

export const FALLBACK_ETF_POOL: FallbackEtfPoolItem[] = [
  {
    etfCode: "510300",
    etfName: "沪深300ETF",
    category: "宽基",
    direction: "大盘",
    trackingIndexCode: "000300.SH",
    trackingIndexName: "沪深300",
    aumYi: 3985,
    avgDailyTurnoverYi: 18.2,
    premiumDiscount: -0.02,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "510500",
    etfName: "中证500ETF",
    category: "宽基",
    direction: "中盘",
    trackingIndexCode: "000905.SH",
    trackingIndexName: "中证500",
    aumYi: 512,
    avgDailyTurnoverYi: 8.9,
    premiumDiscount: -0.04,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "510050",
    etfName: "上证50ETF",
    category: "宽基",
    direction: "大盘",
    trackingIndexCode: "000016.SH",
    trackingIndexName: "上证50",
    aumYi: 620,
    avgDailyTurnoverYi: 10.6,
    premiumDiscount: -0.01,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "159915",
    etfName: "创业板ETF",
    category: "宽基",
    direction: "成长",
    trackingIndexCode: "399006.SZ",
    trackingIndexName: "创业板指",
    aumYi: 642,
    avgDailyTurnoverYi: 12.4,
    premiumDiscount: 0.03,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "588000",
    etfName: "科创50ETF",
    category: "宽基",
    direction: "科技",
    trackingIndexCode: "000688.SH",
    trackingIndexName: "科创50",
    aumYi: 918,
    avgDailyTurnoverYi: 15.6,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "512480",
    etfName: "半导体ETF",
    category: "行业",
    direction: "半导体",
    trackingIndexCode: null,
    trackingIndexName: null,
    aumYi: 210,
    avgDailyTurnoverYi: 5.8,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "159992",
    etfName: "创新药ETF",
    category: "行业",
    direction: "医药",
    trackingIndexCode: null,
    trackingIndexName: null,
    aumYi: 95,
    avgDailyTurnoverYi: 3.2,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "516160",
    etfName: "新能源车ETF",
    category: "行业",
    direction: "新能源",
    trackingIndexCode: "399976.SZ",
    trackingIndexName: "CS新能车",
    aumYi: 145,
    avgDailyTurnoverYi: 4.4,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "515790",
    etfName: "光伏ETF",
    category: "行业",
    direction: "新能源",
    trackingIndexCode: null,
    trackingIndexName: null,
    aumYi: 86,
    avgDailyTurnoverYi: 2.9,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "159819",
    etfName: "人工智能ETF",
    category: "行业",
    direction: "AI",
    trackingIndexCode: "931071.CSI",
    trackingIndexName: "人工智能",
    aumYi: 72,
    avgDailyTurnoverYi: 2.6,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "562800",
    etfName: "芯片ETF",
    category: "行业",
    direction: "半导体",
    trackingIndexCode: null,
    trackingIndexName: null,
    aumYi: 118,
    avgDailyTurnoverYi: 3.7,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "159928",
    etfName: "消费ETF",
    category: "行业",
    direction: "消费",
    trackingIndexCode: null,
    trackingIndexName: null,
    aumYi: 178,
    avgDailyTurnoverYi: 2.8,
    premiumDiscount: -0.06,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "515170",
    etfName: "食品饮料ETF",
    category: "行业",
    direction: "消费",
    trackingIndexCode: "399396.SZ",
    trackingIndexName: "国证食品",
    aumYi: 120,
    avgDailyTurnoverYi: 2.1,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "512880",
    etfName: "证券ETF",
    category: "行业",
    direction: "券商",
    trackingIndexCode: "399975.SZ",
    trackingIndexName: "证券公司",
    aumYi: 260,
    avgDailyTurnoverYi: 7.5,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "512800",
    etfName: "银行ETF",
    category: "行业",
    direction: "银行",
    trackingIndexCode: null,
    trackingIndexName: null,
    aumYi: 105,
    avgDailyTurnoverYi: 2.7,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "159938",
    etfName: "医药卫生ETF",
    category: "行业",
    direction: "医药",
    trackingIndexCode: "000991.SH",
    trackingIndexName: "全指医药",
    aumYi: 128,
    avgDailyTurnoverYi: 3.1,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "515030",
    etfName: "新能源ETF",
    category: "行业",
    direction: "新能源",
    trackingIndexCode: null,
    trackingIndexName: null,
    aumYi: 74,
    avgDailyTurnoverYi: 2.4,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "512660",
    etfName: "军工ETF",
    category: "行业",
    direction: "军工",
    trackingIndexCode: "399967.SZ",
    trackingIndexName: "中证军工",
    aumYi: 134,
    avgDailyTurnoverYi: 3.4,
    premiumDiscount: 0.12,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "512400",
    etfName: "有色金属ETF",
    category: "行业",
    direction: "有色",
    trackingIndexCode: null,
    trackingIndexName: null,
    aumYi: 90,
    avgDailyTurnoverYi: 2.5,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "512980",
    etfName: "传媒ETF",
    category: "行业",
    direction: "传媒",
    trackingIndexCode: "399971.SZ",
    trackingIndexName: "中证传媒",
    aumYi: 68,
    avgDailyTurnoverYi: 1.9,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "562500",
    etfName: "机器人ETF",
    category: "行业",
    direction: "机器人",
    trackingIndexCode: null,
    trackingIndexName: null,
    aumYi: 55,
    avgDailyTurnoverYi: 1.6,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "159828",
    etfName: "医疗ETF",
    category: "行业",
    direction: "医疗",
    trackingIndexCode: "399989.SZ",
    trackingIndexName: "中证医疗",
    aumYi: 112,
    avgDailyTurnoverYi: 2.8,
    premiumDiscount: null,
    expenseRatio: 0.0015,
  },
  {
    etfCode: "513100",
    etfName: "纳指ETF",
    category: "跨境",
    direction: "美股",
    trackingIndexCode: null,
    trackingIndexName: "纳斯达克100",
    aumYi: 312,
    avgDailyTurnoverYi: 6.5,
    premiumDiscount: null,
    expenseRatio: 0.008,
  },
  {
    etfCode: "513500",
    etfName: "标普ETF",
    category: "跨境",
    direction: "美股",
    trackingIndexCode: null,
    trackingIndexName: "标普500",
    aumYi: 180,
    avgDailyTurnoverYi: 4.8,
    premiumDiscount: null,
    expenseRatio: 0.006,
  },
  {
    etfCode: "513050",
    etfName: "中概互联ETF",
    category: "跨境",
    direction: "港股",
    trackingIndexCode: null,
    trackingIndexName: "中概互联",
    aumYi: 205,
    avgDailyTurnoverYi: 5.6,
    premiumDiscount: null,
    expenseRatio: 0.006,
  },
  {
    etfCode: "513180",
    etfName: "恒生科技ETF",
    category: "跨境",
    direction: "港股",
    trackingIndexCode: null,
    trackingIndexName: "恒生科技",
    aumYi: 150,
    avgDailyTurnoverYi: 4.9,
    premiumDiscount: null,
    expenseRatio: 0.006,
  },
  {
    etfCode: "159920",
    etfName: "恒生ETF",
    category: "跨境",
    direction: "港股",
    trackingIndexCode: null,
    trackingIndexName: "恒生指数",
    aumYi: 421,
    avgDailyTurnoverYi: 9.8,
    premiumDiscount: -0.18,
    expenseRatio: 0.0016,
  },
];
